language: ruby
rvm:
- 2.5.1
services:
  - postgresql

before_script:
  - psql -c 'create database bookmark_manager;' -U postgres
  - psql -c 'create database bookmark_manager_test;' -U postgres
script:
- bundle exec rspec spec/
before_install:
- gem update --system
- gem install bundler
after_script:
  - bundle exec rake coveralls:push